name = input("Enter Name: ")
age = input("Enter Age: ")
department = input("Enter Department: ")
university = input("Enter University: ")
mobile = input("Enter Mobile Number: ")
print("\n*********************************")
print("        STUDENT BIO CARD         ")
print("*********************************")
print("Name        : ", name)
print("Age         : ", age)
print("Department  : ", department)
print("University  : ", university)
print("Mobile      : ", mobile)
print("*********************************")
