p1 = int(input())
p2 = int(input())
print("Total price:", p1 + p2)
print("Price difference:", max(p1, p2) - min(p1, p2))
print("Product of the prices:", p1 * p2)
print("Division of the first price by second price:", p1 / p2)
print("Remainder:", p1 % p2)
print("Floor division:", p1 // p2)
