print(type(25))
print(type(25.0))
print(type('25'))
print(type("Python"))
print(type(True))
print(type(False))
print(type(3 + 4j))
print(type(-18))
print(type('True'))
print(type(0.0))
print(type('3+4j'))
print(type(0))
