name = input("Enter Name: ")
age = input("Enter Age: ")
dept = input("Enter Department: ")
univ = input("Enter University: ")
mob = input("Enter Mobile Number: ")
print("*" * 33)
print("        STUDENT BIO CARD         ")
print("*" * 33)
print("Name        : " + name)
print("Age         : " + age)
print("Department  : " + dept)
print("University  : " + univ)
print("Mobile      : " + mob)
print("*" * 33)
