price1 = int(input())
price2 = int(input())
print("Total price:", price1 + price2)
print("Price difference:", abs(price1 - price2))
print("Product of the prices:", price1 * price2)
print("Division of the first price by second price:", price1 / price2)
print("Remainder:", price1 % price2)
print("Floor division:", price1 // price2)
